### ISSUE TITLE
Update the documentation about `hoa core:*`

### ISSUE THREAD

**Issue by Hywan** [hoaproject/Devtools#1]
See https://github.com/hoaproject/Central/issues/15.

**Comment by Hywan** [comment]
I am assigning @camael24 on this one :-). You have to dig Literature.git and maybe all hack book chapters.

**Comment by Jir4** [comment]
So now that Hoa\Core is dead, what should we do with this issue ?

**Comment by Hywan** [comment]
Nothing. It has alreay been updated.

Thanks!
