### ISSUE TITLE
cs-fixer: remove constructors return tag.

### ISSUE THREAD

**Issue by Metalaka** [hoaproject/Devtools#12]
I propose to add a cs-fixer which remove the PHPDoc `@return` tag of constructors.
Since they are [optional](http://www.phpdoc.org/docs/latest/references/phpdoc/tags/return.html) and current `@return void` is invalid, it can be a good thing :)

**Comment by Hywan** [comment]
`@return void` is not invalid as far as I know, it can just be ommited. And I like explicit stuff, so I would go for :-1: but we can ask other @hoaproject/hoackers!

**Comment by marmotz** [comment]
A constructor never return anything. It's not an explicit stuff, it's a useless stuff.

**Comment by Hywan** [comment]
@marmotz It's consistent with other method at least. Since it returns nothing, we can say it returns nothing.

**Comment by Metalaka** [comment]
> @return void is not invalid as far as I know
> 
> constructors, the @return tag MAY be omitted here, in which case @return **self** is implied.

IMO, that mean the only valid value for a constructor is `self`.

So, solutions are:
- remove the tag and use the default value
- Set value to `self`

**Comment by Hywan** [comment]
`@return self` seems better for me.

**Comment by jubianchi** [comment]
IMHO, `return self` is useless: we all know the constructor implicitly returns (through `new`) an instace of the class.

Such metadata is not useful for IDEs (they already handle everything the right way) or for doc generators (developers know what a constructor does). It will just create more work but no value.

**Comment by Hywan** [comment]
So let's go for a `@return` removal if set to `void`?

**Comment by marmotz** [comment]
+1 @jubianchi

**Comment by jubianchi** [comment]
@Hywan :+1:

`return void` makes sense on methods, even if modern IDEs handle this case when they do not find any `return` statement, I think it might be useful for documentation.

My only concern was about `@return` on constructors.

**Comment by marmotz** [comment]
Exactly what i say in my very first comment :)

**Comment by Hywan** [comment]
ping?

**Comment by Metalaka** [comment]
@Hywan look at #29

**Comment by Hywan** [comment]
Commented #29.
