### ISSUE TITLE
Merge Hoathis\Documentation into Hoa\Devtools

### ISSUE THREAD

**Issue by Hywan** [hoaproject/Devtools#14]
Hello :smiley:,

I was thinking about simplifying the contribution process and thought: What about merging the [the `Hoathis\Documentation` tool](https://github.com/hoaproject/Hoathis-Documentation) into this library. For me it makes sense:
- Less repository to maintain (which is good!),
- One place for all devtools,
- Ease the contribution (you install `hoa/test` which install `hoa/devtools` and here you go, or you install `hoa/devtools` and here you go).

Thoughts @hoaproject/hoackers?

**Comment by osaris** [comment]
If it can ease the contribution process it's perfect and as you say, it's one less repository to maintain so big +1 for me.

**Comment by Hywan** [comment]
Perfect :-). Thanks!
