### ISSUE TITLE
Create the `hoa devtools:check`

### ISSUE THREAD

**Issue by Hywan** [hoaproject/Devtools#2]
Maybe we should name this command differently, like `hoa devtools:configure`, I don't know, or maybe `hoa devtools:caniuse` or `devtools:iscompatible`.

`hoa test:run` should also run this command before running tests.

See https://github.com/hoaproject/Central/issues/15.

**Comment by Hywan** [comment]
`hoa devtools:checkconfiguration` is proposed in https://github.com/hoaproject/Central/issues/15 also.

**Comment by Hywan** [comment]
Maybe @vonglasow would like to do this one?

**Comment by vonglasow** [comment]
@Hywan yep why not ;) see also https://github.com/hoaproject/Core/issues/61

**Comment by shulard** [comment]
Hello,

What's the meaning of that `devtools:check` command today ? Is it still relevant ?

**Comment by Hywan** [comment]
You're right, we can close it.
