### ISSUE TITLE
vendor/bin/hoa without arguments = errors

### ISSUE THREAD

**Issue by Grummfy** [hoaproject/Devtools#45]
When you run the command without arguments, you get an error
> $ vendor/bin/hoa 
> Hoa\Dispatcher\ClassMethod::resolve(): (0) Class Hoa\Cli\Bin\Welcome is not found (method: GET, asynchronous: false).
> in /home/jvb/workspace/_perso/hoa/Compiler/vendor/hoa/dispatcher/ClassMethod.php at line 101.
> 
>     ⬇
> 
> Nested exception (ReflectionException):
> Class Hoa\Cli\Bin\Welcome does not exist
> 

I'm running PHP 7.0.18-0ubuntu0.17.04.1

**Comment by Hywan** [comment]
I cannot reproduce. How did you install it? Do you have `hoa/cli` installed (I suppose yes, but…)? Do you have the `vendor/hoa/cli/Bin/Welcome.php` file?

**Comment by Grummfy** [comment]
I just run composer install on several libs. So hoa/cli is a dependency, at least for dev, so itshould not be an error

**Comment by Hywan** [comment]
Please, reply to all the questions :-).

**Comment by Grummfy** [comment]
lol
>How did you install it?
composer install
>Do you have hoa/cli instealled (I suppose yes, but…)?
with the dependency, yes
if I take hoa/acl

> 
> composer show
> atoum/atoum                3.0.0      Simple modern and intuitive unit testing framework for PHP 5.3+
> atoum/praspel-extension    0.17.02.24 Include Praspel inside atoum.
> atoum/ruler-extension      1.3.0      The atoum ruler-extension allows you to filter your tests using Hoa\Ruler
> atoum/visibility-extension 1.3.0      atoum extension to loosen method visibility
> hoa/cli                    2.17.01.11 The Hoa\Cli library.
> hoa/compiler               3.17.01.10 The Hoa\Compiler library.
> hoa/consistency            1.17.05.02 The Hoa\Consistency library.
> hoa/console                3.17.05.02 The Hoa\Console library.
> hoa/devtools               1.17.02.24 The Hoa\Devtools library.
> hoa/dispatcher             1.17.05.02 The Hoa\Dispatcher library.
> hoa/event                  1.17.01.13 The Hoa\Event library.
> hoa/exception              1.17.01.16 The Hoa\Exception library.
> hoa/file                   1.17.01.13 The Hoa\File library.
> hoa/graph                  1.17.01.13 The Hoa\Graph library.
> hoa/http                   1.17.01.13 The Hoa\Http library.
> hoa/iterator               2.17.01.10 The Hoa\Iterator library.
> hoa/locale                 2.17.01.10 The Hoa\Locale library.
> hoa/math                   1.17.05.16 The Hoa\Math library.
> hoa/praspel                1.17.01.10 The Hoa\Praspel library.
> hoa/protocol               1.17.01.14 The Hoa\Protocol library.
> hoa/realdom                1.17.01.13 The Hoa\Realdom library.
> hoa/regex                  1.17.01.13 The Hoa\Regex library.
> hoa/router                 3.17.01.14 The Hoa\Router library.
> hoa/ruler                  2.17.05.16 The Hoa\Ruler library.
> hoa/stream                 1.17.02.21 The Hoa\Stream library.
> hoa/stringbuffer           1.17.01.16 The Hoa\Stringbuffer library.
> hoa/test                   2.17.02.27 The Hoa\Test library.
> hoa/ustring                4.17.01.16 The Hoa\Ustring library.
> hoa/view                   3.17.01.14 The Hoa\View library.
> hoa/visitor                2.17.01.16 The Hoa\Visitor library.
> hoa/xml                    1.17.01.16 The Hoa\Xml library.
> hoa/xyl                    1.17.01.16 The Hoa\Xyl library.
> hoa/zformat                1.17.01.10 The Hoa\Zformat library.

Do you have the vendor/hoa/cli/Bin/Welcome.php file?
Yes

> ls vendor/hoa/cli/Bin/
> hoa  hoa.bat  Hoa.php  Welcome.php
>

**Comment by Hywan** [comment]
Remove everything and restart. Still the issue?

**Comment by Grummfy** [comment]
yes

**Comment by Grummfy** [comment]
for information Bin/hoa cli:welcome do the same  error (I try on the cli repository itself)

**Comment by Hywan** [comment]
I am still not able to reproduce :-/. Anyone else @hoaproject/hoackers?

**Comment by Grummfy** [comment]
I try on repository of hoa/cli, hoa/acl, ... same result.
I'm running PHP 7.0.18-0ubuntu0.17.04.1

**Comment by Pierozi** [comment]
A good one @Grummfy thanks.

**Comment by Hywan** [comment]
For the record, [`hoa/cli` 2.17.07.12 has been released](https://github.com/hoaproject/Cli/releases/tag/2.17.07.12).

**Comment by Grummfy** [comment]
thanks
